/**
 * @license Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

var CKBUILDER_CONFIG = {
	//skin: null,
	skin: 'moono',
	ignore: [
		'dev',
		'README.md',
		'CHANGES.md',
		'LICENSE.md',
		'samples',
		'skins/kama',
		//'lang',
	'plugins/a11yhelp',
	'plugins/about',
	'plugins/adobeair',
	'plugins/ajax',
	'plugins/autogrow',
	'plugins/bbcode',
	'plugins/bidi',
	'plugins/blockquote',
//'plugins/button',
//'plugins/colorbutton',
//'plugins/colordialog',
//'plugins/contextmenu',
	'plugins/devtools',
//'plugins/dialog',
//'plugins/dialogadvtab',
//'plugins/dialogui',
	'plugins/div',
	'plugins/divarea',
	'plugins/docprops',
	'plugins/elementspath',
	'plugins/enterkey',
//'plugins/entities',
	'plugins/fakeobjects',
	'plugins/filebrowser',
	'plugins/find',
	'plugins/flash',
//'plugins/floatingspace',
//'plugins/floatpanel',
	'plugins/font',
	'plugins/format',
//'plugins/forms',
//'plugins/iframe',
//'plugins/iframedialog',
	'plugins/image',
	'plugins/image2',
	'plugins/language',
//'plugins/lineutils',
	'plugins/link',
	'plugins/listblock',
	'plugins/liststyle',
	'plugins/magicline',
	'plugins/mathjax',
//'plugins/menu',
//'plugins/menubutton',
	'plugins/newpage',
	'plugins/pagebreak',
//'plugins/panel',
//'plugins/panelbutton',
	'plugins/placeholder',
	'plugins/popup',
	'plugins/preview',
	'plugins/print',
	'plugins/richcombo',
	'plugins/save',
	'plugins/selectall',
	'plugins/sharedspace',
	'plugins/showblocks',
	'plugins/showborders',
	'plugins/smiley',
	'plugins/sourcearea',
	'plugins/sourcedialog',
	'plugins/specialchar',
	'plugins/stylescombo',
	'plugins/stylessheetparser',
	'plugins/tab',
	'plugins/templates',
	'plugins/toolbar',
	'plugins/uicolor',
	'plugins/xml',
		'.gitignore',
		'.gitattributes',
		'.idea',
		'.mailmap',
		'.DS_Store'
	],
	plugins: {
		basicstyles: 1,
		clipboard: 1,
		horizontalrule: 1,
		htmlwriter: 1,
		indent: 1,
		indentlist: 1,
		indentblock: 1,
		justify: 1,
		list: 1,
		maximize: 1,
		pastefromword: 1,
		pastetext: 1,
		removeformat: 1,
		resize: 1,
		table: 1,
		tableresize: 1,
		tabletools: 1,
		undo: 1,
		wysiwygarea: 1,
		widget: 1
	}
};
